ngr_website/core/urls.py
from django.urls import path
from .views import AboutUs, ContactUs, Home, email_subscription

app_name = 'core'

urlpatterns = [
    path('', Home.as_view(), name='home'),
    path('about-us/', AboutUs.as_view(), name='about_us'),
    path('contact-us/', ContactUs.as_view(), name='contact_us'),
    path('email-subscription', email_subscription, name='email_subscription'),
    # path('email-subscription', EmailSubscription.as_view(), name='email_subscription')
]

ngr_website/ngr_website/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import include, path

admin.site.site_header = 'Admin Login'

handler404 = 'core.views.custom_page_not_found_view'
handler500 = 'core.views.custom_error_view'
handler403 = 'core.views.custom_permission_denied_view'
handler400 = 'core.views.custom_bad_request_view'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('contest/', include('contest.urls'))
]


if bool(settings.DEBUG):
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

ngr_website/core/models.py
from django.db import models

from contest.models import TimeStampModel

# Create your models here.


class EmailSubscription(TimeStampModel):
    email = models.EmailField(max_length=200)
    verified = models.BooleanField(default=False)

    def __str__(self):
        return self.email

ngr_website/core/forms.py
from django import forms
from .models import EmailSubscription
from captcha import fields, widgets
from django.utils.translation import gettext_lazy as _


class EmailSubscriptionForm(forms.ModelForm):
    """
    Email Subscription form.
    """
    email = forms.EmailField(label=_(''), widget=forms.EmailInput(attrs={'class':'me-1 px-2', 'placeholder':"Enter your email", "style": "height: 40px; border: none; width: 90%;"}))
    recaptcha = fields.ReCaptchaField(label='', widget=widgets.ReCaptchaV2Invisible)    
    class Meta:
        model = EmailSubscription
        fields = ('email',)
        


class ContactForm(forms.Form):
    last_name = forms.CharField(label=_('Last Name'), widget=forms.TextInput(attrs={'class':'form-control' })) 
    other_names = forms.CharField(label=_('Other Names'), widget=forms.TextInput(attrs={'class':'form-control' }))   
    email = forms.EmailField(label=_('Email'), widget=forms.EmailInput(attrs={'class':'form-control'}))
    message = forms.CharField(label=_('Message'), widget=forms.Textarea(attrs={'class':'form-control', 'rows':"12", 'placeholder':"Type the message you wish to send"}))
    recaptcha = fields.ReCaptchaField(label='', widget=widgets.ReCaptchaV2Invisible)

ngr_website/core/views.py
from django.views.generic import TemplateView
from django.core.mail import send_mail
from django.shortcuts import redirect, render
from django.views.generic.base import View

from .models import EmailSubscription
from .forms import ContactForm, EmailSubscriptionForm
from django.views.generic import FormView, TemplateView
from django.urls import reverse_lazy
from django.contrib import messages
from django.utils.safestring import mark_safe
from django.core.mail import send_mail
import asyncio


# Create your views here.

class Home(TemplateView):
    template_name = 'core/home.html'

class AboutUs(TemplateView):
    template_name = 'core/about-us.html'

class ContactUs(FormView):
    form_class = ContactForm
    template_name = 'core/contact-us.html'
    success_url = reverse_lazy('core:contact_us')

    def form_valid(self, form):
        """If the form is valid, redirect to the supplied URL."""
        subject = f'NGR Contact Form'
        from_email = 'NGR <gigantlimited@gmail.com>'
        to_email = 'naijagracerace@gmail.com'
        last_name = form.cleaned_data['last_name']
        other_names = form.cleaned_data['other_names']
        email = form.cleaned_data['email']
        message = form.cleaned_data['message']
        try:
            send_mail(
                subject,
                f'Email: {email}\nLast Name: {last_name}\nOther Names: {other_names}\n\nMessage: {message}',
                from_email,
                [to_email],
                fail_silently=False,
            )
            messages.success(self.request, mark_safe(f'Your message has been sent!'))
        except:
            self.render_to_response(self.get_context_data(form=form))
            messages.error(self.request, mark_safe(f'Error! Message not sent!'))
        return super().form_valid(form)

    def form_invalid(self, form):
        """If the form is invalid, render the invalid form."""
        messages.error(self.request, mark_safe(f'Error! Message not sent!'))
        return self.render_to_response(self.get_context_data(form=form))



def email_subscription(request):
    form = EmailSubscriptionForm
    if request.method == 'POST':
        form = form(request.POST)
        if form.is_valid():
            email = form.cleaned_data.get('email')
            if EmailSubscription.objects.filter(email=email).exists():
                messages.error(request, mark_safe('Email already exist'))
                return redirect(request.META.get('HTTP_REFERER'))
            else:
                form.save()
                messages.success(request, mark_safe('Email submitted successfully'))
                return redirect(request.META.get('HTTP_REFERER'))
        else:
            messages.error(request, mark_safe('Error submitting email'))
            return redirect(request.META.get('HTTP_REFERER'))
    return render(request, 'base.html', {'subscription_form':form})


# class EmailSubscription(View):
#     form = EmailSubscriptionForm
#     def get(self):
#         return render(self.request, 'base.html', {'subscription_form':self.form})
    
#     def post(self):
#         form = self.form(self.request.POST)
#         if form.is_valid():
#             email = form.cleaned_data.get('email')
#             if EmailSubscription.objects.filter(email=email).exists():
#                 messages.error(self.request, mark_safe('Email already exist'))
#                 return redirect(self.request.META.get('HTTP_REFERER'))
#             else:
#                 form.save()
#                 messages.success(self.request, mark_safe('Email submitted successfully'))
#                 return redirect(self.request.META.get('HTTP_REFERER'))
#         else:
#             messages.error(self.request, mark_safe('Error submitting email'))
#             return redirect(self.request.META.get('HTTP_REFERER'))




def custom_page_not_found_view(request, exception):
    return render(request, "errors/404.html", {})

def custom_error_view(request, exception=None):
    return render(request, "errors/500.html", {})

def custom_permission_denied_view(request, exception=None):
    return render(request, "errors/403.html", {})

def custom_bad_request_view(request, exception=None):
    return render(request, "errors/400.html", {})   

ngr_website/core/templates/includes/alert.html
{% if messages %}
<ul id="alert-message" class="messages">
    {% for message in messages %}
    <li class="text-center fixed-top message-{{ message.tags }} text-white" data-aos="slide-down"
        data-aos-duration="900" style="z-index: 1100;width: 100vw; text-decoration: none; list-style-type: none;">
        {{message}}
    </li>
    {% endfor %}
</ul>
{% endif %}

ngr_website/core/templates/includes/banner.html
{% load humanize %}

<div class="d-flex align-items-center" style="height: 50px;background-color: #1FB07C;width: 100%;">
    <h4 style="color: #ffffff;width: 100%;">
        <marquee>Naija Grace Race, 1st race ({{ contest }}), registration and voting is ongoing...     The contest ends on the 31st of January 2022.     1st prize N50,000, 2nd prize N30,000 and 3rd prize N20,000</marquee>
    </h4>
</div>

ngr_website/core/templates/includes/footer.html
{% load widget_tweaks %}

<div class="d-flex justify-content-center py-2">
    <hr class="d-none d-lg-block" style="width: 90%;">
</div>
<footer>
    <div class="row" id="footer">
        <div class="col-sm-12 col-md-4 col-lg-3 order-sm-1 my-3" style="color: #ffffff;">
            <h1 style="font-size: 24px;color: #FFFFFF;font-weight: bold;">Naija Grace Race</h1>
            <p style="font-size: 16px;margin-top: 30px;font-weight: lighter;">was established in the year 2021 as a platform to create an opportunity for the young talented ones who has no one to appreciate or encourage them. It is a platform where all talented ones are welcomed and age is not a barrier.</p>
        </div>
        <div class="col-sm-12 col-md-4 col-lg-3 text-md-center d-inline-flex d-md-block justify-content-between order-sm-2 my-3">
            <p><i class="fas fa-map-marker-alt me-3 d-none d-md-inline" style="color: #333D5F;"></i><span class="d-md-none me-3"><svg width="22" height="22" viewBox="0 0 22 22" fill="none" xmlns="http://www.w3.org/2000/svg">
<circle cx="11" cy="11" r="11" fill="white"/>
<path fill-rule="evenodd" clip-rule="evenodd" d="M11.8856 15.8423C13.2573 14.8245 15.5985 12.7247 15.5985 10.25C15.5985 7.62665 13.5018 5.5 10.9155 5.5C8.32909 5.5 6.23242 7.62665 6.23242 10.25C6.23242 12.7247 8.57362 14.8245 9.94529 15.8423C10.5276 16.2744 11.3034 16.2744 11.8856 15.8423ZM10.9155 11.75C11.7323 11.75 12.3944 11.0784 12.3944 10.25C12.3944 9.42155 11.7323 8.74998 10.9155 8.74998C10.0988 8.74998 9.43667 9.42155 9.43667 10.25C9.43667 11.0784 10.0988 11.75 10.9155 11.75Z" fill="#333D5F"/>
</svg>
</span><span style="font-size: 16px;color: #ffffff;">Abuja, Nigeria</span></p>
            <p><i class="fas fa-phone-alt me-3 d-none d-md-inline" style="color: #333D5F;"></i><span class="d-md-none me-3"><svg width="22" height="22" viewBox="0 0 22 22" fill="none" xmlns="http://www.w3.org/2000/svg">
<circle cx="11" cy="11" r="11" fill="white"/>
<path d="M13.0584 13.9525L12.7491 14.4231C12.6874 14.517 12.6057 14.5972 12.4981 14.626C12.1457 14.7205 11.2099 14.7632 9.7853 13.3181C8.36066 11.8731 8.40271 10.9239 8.49585 10.5664C8.52428 10.4573 8.6033 10.3744 8.6959 10.3118L9.15985 9.99808C9.50527 9.7645 9.59861 9.29112 9.36833 8.94075L8.49208 7.60755C8.29109 7.30173 7.9036 7.18489 7.57054 7.32967L7.17526 7.5015C6.87499 7.63204 6.63004 7.8663 6.48394 8.16269C6.36188 8.41031 6.26728 8.67107 6.25446 8.94762C6.21406 9.81912 6.40246 11.9662 8.76028 14.3578C11.1181 16.7494 13.2349 16.9405 14.0941 16.8995C14.3667 16.8865 14.6238 16.7906 14.8679 16.6668C15.1601 16.5186 15.3911 16.2701 15.5197 15.9655L15.6891 15.5646C15.8319 15.2268 15.7167 14.8337 15.4152 14.6299L14.1008 13.7411C13.7554 13.5075 13.2887 13.6022 13.0584 13.9525Z" fill="#333D5F"/>
</svg></span><span style="font-size: 16px;color: #ffffff;">{{ phone_number }}</span></p>
        </div>
        <div class="col-sm-12 col-md-12 col-lg-3 d-flex justify-content-center order-sm-3 order-md-4 order-lg-3 my-3">
            <div class="py-4 home-social-icons"><a href="{{ facebook }}" style="fill: #333D5F;"><svg width="34" height="34" viewBox="0 0 34 34">
                <path d="M17 0C7.61113 0 0 7.61113 0 17C0 26.3889 7.61113 34 17 34C26.3889 34 34 26.3889 34 17C34 7.61113 26.3889 0 17 0ZM23.4856 8.65739L21.1343 8.65843C19.2904 8.65843 18.9339 9.53461 18.9339 10.8202V13.655H23.3308L23.3287 18.095H18.9343V29.489H14.3482V18.095H10.5144V13.655H14.3482V10.3805C14.3482 6.58052 16.6699 4.51096 20.0595 4.51096L23.4859 4.51617V8.65739H23.4856Z"></path>
            </svg></a><a class="mx-3" href="{{ instagram }}" style="fill: #333D5F;"><svg width="33" height="34" viewBox="0 0 33 34">
                <path d="M21.4916 9.04565H11.8406C10.3001 9.04565 9.04688 10.3616 9.04688 11.9791V22.1126C9.04688 23.7301 10.3001 25.0464 11.8406 25.0464H21.4916C23.032 25.0464 24.2857 23.7305 24.2857 22.1126V11.9791C24.2857 10.3616 23.0324 9.04565 21.4916 9.04565ZM16.6661 22.3134C13.9002 22.3134 11.6497 19.9504 11.6497 17.0458C11.6497 14.1416 13.9002 11.7787 16.6661 11.7787C19.4324 11.7787 21.6828 14.1416 21.6828 17.0458C21.6828 19.9501 19.432 22.3134 16.6661 22.3134ZM21.8441 12.8677C21.1893 12.8677 20.6568 12.3086 20.6568 11.6215C20.6568 10.9343 21.1893 10.3752 21.8441 10.3752C22.4985 10.3752 23.031 10.9343 23.031 11.6215C23.031 12.3086 22.4985 12.8677 21.8441 12.8677Z"></path>
                <path d="M16.6664 14.0045C15.0697 14.0045 13.7695 15.3689 13.7695 17.0455C13.7695 18.7228 15.0697 20.0876 16.6664 20.0876C18.2639 20.0876 19.5629 18.7228 19.5629 17.0455C19.5629 15.3693 18.2635 14.0045 16.6664 14.0045Z"></path>
                <path d="M16.667 0C7.72564 0 0.476562 7.61153 0.476562 17C0.476562 26.3885 7.72564 34 16.667 34C25.6084 34 32.8575 26.3885 32.8575 17C32.8575 7.61153 25.6084 0 16.667 0ZM26.4061 22.1126C26.4061 24.9578 24.2022 27.2718 21.4925 27.2718H11.8415C9.13224 27.2718 6.928 24.9578 6.928 22.1126V11.9791C6.928 9.13429 9.13224 6.81985 11.8415 6.81985H21.4925C24.2022 6.81985 26.4061 9.13429 26.4061 11.9791V22.1126Z"></path>
            </svg></a><a href="{{ twitter }}" style="fill: #333D5F; display:none"><svg width="35" height="34" viewBox="0 0 35 34">
                <path d="M17.334 0C7.94658 0 0.333984 7.61259 0.333984 17C0.333984 26.3874 7.94658 34 17.334 34C26.7214 34 34.334 26.3874 34.334 17C34.334 7.61259 26.7214 0 17.334 0ZM25.096 13.2548C25.1035 13.4221 25.1071 13.5902 25.1071 13.7591C25.1071 18.9151 21.1824 24.8608 14.0051 24.8611H14.0054H14.0051C11.8015 24.8611 9.75096 24.2152 8.02414 23.1083C8.32945 23.1444 8.64021 23.1623 8.95486 23.1623C10.7831 23.1623 12.4656 22.5387 13.8012 21.492C12.0931 21.4604 10.6529 20.3322 10.1559 18.7818C10.3938 18.8275 10.6384 18.8524 10.8892 18.8524C11.2454 18.8524 11.5904 18.8044 11.9182 18.7149C10.1328 18.3574 8.78781 16.7795 8.78781 14.89C8.78781 14.8724 8.78781 14.8566 8.78833 14.8402C9.31413 15.1326 9.91542 15.3085 10.5556 15.3282C9.5079 14.6291 8.8192 13.434 8.8192 12.0802C8.8192 11.3653 9.01245 10.6956 9.3476 10.1189C11.2718 12.48 14.1475 14.0327 17.3905 14.1959C17.3236 13.91 17.2891 13.6122 17.2891 13.3062C17.2891 11.1521 19.0367 9.40453 21.1915 9.40453C22.3139 9.40453 23.3277 9.87897 24.0397 10.6375C24.9287 10.4621 25.7634 10.1373 26.5175 9.69038C26.2257 10.6011 25.6073 11.3653 24.8016 11.8486C25.5909 11.7542 26.3432 11.5448 27.0423 11.2341C26.5201 12.0167 25.8578 12.7041 25.096 13.2548Z"></path>
            </svg></a></div>
        </div>
            <form action="{% url 'core:email_subscription' %}" class="col-sm-12 col-md-4 col-lg-3 order-sm-4 order-md-3 my-md-3 mt-5 mt-5 needs-validation" method="post">
                <h1 style="font-size: 18px;color: #333D5F;font-weight: bold;">Stay Updated</h1>
                {% csrf_token %}   
                {% for hidden_field in form.hidden_fields %}
                {{ hidden_field }}
                {% endfor %}
    
                    <div class="row">
                    <div class="d-flex">
                        {% render_field subscription_form.email  %}                        
                        <button class="btn btn-primary" type="submit" style="border-radius: 0px;background-color: #333D5F;height: 40px;width: 46px;border: none;"><i class="fab fa-telegram-plane"></i></button>
                    </div>
                </div>
                {% if subscription_form.email.help_text %}
                <small class="form-text text-muted">{{ subscription_form.email.help_text }}</small>
                {% endif %}
                {% if subscription_form.non_field_errors %}
                <small class="alert alert-danger" role="alert">
                    {% for error in subscription_form.non_field_errors %}
                    {{ error }}
                    {% endfor %}
                </small>
                {% endif %}
                    {% render_field subscription_form.recaptcha %}                        





        </form>
    </div>
</footer>

ngr_website/core/templates/includes/pagination.html
<div class="text-center d-flex justify-content-center align-items-center py-5">
  {% if page_obj.has_previous %}
  <a href="?page={{ page_obj.previous_page_number }}" aria-label="Previous"
    style="text-decoration: none;color: #000000;font-size: 18px;"><i class="fas fa-chevron-left m-3"></i></a>
  {% else %}
  <a class="disabled" href="#" style="text-decoration: none;color: #000000;font-size: 18px;"><i
      class="fas fa-chevron-left m-3"></i></a>

  {% endif %}
  {% for num in page_obj.paginator.page_range %}
  {% if page_obj.number == num %}
  <a href="?page={{num}}" style=" text-decoration: none;">
    <div class="paginate mx-1" style="background-color:#333D5F;">
      <p>{{num}}</p>
    </div>
  </a>
  {% elif num > page_obj.number|add:'-6' and num < page_obj.number|add:'6' %} <a href="?page={{num}}"
    style="text-decoration: none;">
    <div class="paginate mx-1">
      <p>{{num}}</p>
    </div>
    </a>

    {% endif %}
    {% endfor %}

    {% if page_obj.has_next %}
    <a href="?page={{ page_obj.next_page_number }}" aria-label="Next"
      style="text-decoration: none;color: #000000;font-size: 18px;"><i class="fas fa-chevron-right mx-3"></i></a>
    {% else %}
    <a class="disabled" href="#" style="text-decoration: none;color: #000000;font-size: 18px;"><i
        class="fas fa-chevron-right mx-3"></i></a>
    {% endif %}

</div>